### ISSUE TITLE
Linux系统运行源码失败

### ISSUE THREAD

**Issue by LnightSama** [xieyumc/YuYuWechat#7]
Error: ValueError: _type_ 'v' not supported

Traceback (most recent call last):
  File "GradioMain.py", line 3, in <module>
    from SendMessageOnce import SendMessageOnce
  File "/usr/local/src/YuYuWechat-main/SendMessageOnce.py", line 5, in <module>
    import AutoWechat
  File "/usr/local/src/YuYuWechat-main/AutoWechat.py", line 2, in <module>
    import uiautomation as auto
  File "/usr/local/python3/lib/python3.8/site-packages/uiautomation/__init__.py", line 4, in <module>
    from .uiautomation import *
  File "/usr/local/python3/lib/python3.8/site-packages/uiautomation/uiautomation.py", line 23, in <module>
    import ctypes.wintypes
  File "/usr/local/python3/lib/python3.8/ctypes/wintypes.py", line 20, in <module>
    class VARIANT_BOOL(ctypes._SimpleCData):
ValueError: _type_ 'v' not supported

环境： python 3.8.0
服务器： Linux version 3.10.0-1160.102.1.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) ) #1 SMP Tue Oct 17 15:42:21 UTC 2023

**Comment by xieyumc** [comment]
本项目依赖的uiautomation只在win上有，同时本项目也只对win的微信做了适配
